apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default

  source:
    helm:
      releaseName: httpbin
    chart: httpbin
    repoURL: "https://matheusfm.dev/charts"
    targetRevision: 0.1.1

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true